name: Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v4
      with:
        name: hello-artifact
        path: hello.txt

  download:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name : download artifact
      uses: actions/download-artifact@v4
      with:
        name: hello-artifact
        path: ./artifacts/hello.txt
    - name: display artifact
      run: cat ./artifacts/hello.txt

